### ISSUE TITLE
Problem on Arch and Mac

### ISSUE THREAD

**Issue by Enrico68** [lambdalisue/vim-shareboard#7]
Tried to install on both systems. Shareboard does not open in Vim. When I enter the command 
`$ shareboard set "Hello" --filename "Hello.html"`  

```
Traceback (most recent call last):
  File "/usr/bin/shareboard", line 114, in <module>
    main()
  File "/usr/bin/shareboard", line 111, in main
    args.func(args)
  File "/usr/bin/shareboard", line 60, in set
    requests.post(url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 94, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))

```

**Comment by lambdalisue** [comment]
Hum... Could you check your firewall setting? Shareboard use 8081 (default) thus if the port is protected, it might raise ConnectionError.

**Comment by Enrico68** [comment]
I managed to get it works on Arch (forgot to install PySide ..sorry).But  on Mac when I try get a preview it opens with blank screen..
